### ISSUE TITLE
Need a bit more detail in README.md under Test run section

### ISSUE THREAD

**Issue by GodloveD** [AlexanderDilthey/HLA-PRG-LA#1]
I'm trying to install HLA-PRG-LA on the NIH Biowulf cluster.  I'd like to complete the steps in the 'Test run' section.  Can you please include the actual command(s) needed to run HLA-PRG-LA on the NA12878.cram dataset?

I'm also very happy that you have provided a dataset for testing and validation.  I wish more developers would do so.   But the dataset is very large and takes a long time to download.  Is it possible to create a smaller dataset for testing?  If it's small enough, perhaps it could be packaged as part of the installation so that a separate download isn't necessary.  

Thank you.

**Comment by AlexanderDilthey** [comment]
Hi,

The command is

./inferHLATypes.pl --BAM NA12878.cram --graph PRG_MHC_GRCh38_withIMGT --sampleID NA12878 --maxThreads 7

which will generate a file ../working/NA12878_CRAM_replicate/hla/R1_bestguess_G.txt, the output of which should mention the results file provided for download (in terms of inferred alleles).

Providing a smaller-sized input file is a double-edged sword - on the one hand I totally follow your point, but on the other hand I think it's always good to test on some real sample data (and some problems might only happen when applying the algorithm to such data). Perhaps it would be possible to add an additional, smaller test case. Thank you for your suggestion!

**Comment by Valeriia-arh** [comment]
Hello, I am trying to do "make all". I changed the makefile a little bit, but there is such a mistake:

g++ -I/soft/boost/lib -I/soft/bamtools/bamtools-master/include -I/soft/bamtools/bamtools-master/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Graph/Edge.cpp -c -o ../obj/Edge.o
In file included from Graph/Edge.cpp:8:0:
Graph/Edge.h:14:43: fatal error: boost/archive/text_oarchive.hpp: No such file or directory
 #include <boost/archive/text_oarchive.hpp>
                                           ^
compilation terminated.
make: *** [../obj/Edge.o] Error 1


What shall I do? Please, help

**Comment by AlexanderDilthey** [comment]
HLA*PRG:LA now working and installed on NIH biowulf cluster.
