### ISSUE TITLE
update makefile for current bamtools, boost

### ISSUE THREAD

**Issue by andrewrech** [AlexanderDilthey/HLA-PRG-LA#10]
Hello,

Thank you for providing this excellent software. Would you consider updating your makefile to work with the current bamtools repo and boost libraries in $HOME, to ease installation for new users?

See [bamtools](https://github.com/pezmaster31/bamtools/issues/50).

```
BOOST_INCLUDE = {$HOME}/boost/boost_1_64_0/install/include
BOOST_LIB = {$HOME}/boost/boost_1_64_0/install/lib
BAMTOOLS_INCLUDE = {$HOME}/bamtools/include/api

BAMTOOLS_SRC = {$HOME}/bamtools/src
BAMTOOLS_LIB = {$HOME}/bamtools/lib

INCS = -I$(BOOST_INCLUDE) -I$(BAMTOOLS_INCLUDE) -I$(BAMTOOLS_SRC)
LIBS = -L$(BOOST_LIB) -L$(BAMTOOLS_LIB) -lboost_random -lboost_filesystem -lboost_system  -lbamtools -lbamtools-utils -lz -lboost_serialization

```

and

export `LD_LIBRARY_PATH="{$HOME}/bamtools/lib:$LD_LIBRARY_PATH"`

Let me know if you would like a PR to update the makefile and README. Thanks!

Andrew

**Comment by serge2016** [comment]
@andrewrech did you successfully launch the software?

**Comment by andrewrech** [comment]
@serge2016  Thank you. Yes, I am able to compile the software. I would like the makefile to be standardized so this is easier for users who choose not to use docker.

**Comment by serge2016** [comment]
@andrewrech I can compile it too, but I can't process the test. It fails as described in #5

**Comment by andrewrech** [comment]
@serge2016 I don't understand why #5 is related to the issue I have opened here?

**Comment by serge2016** [comment]
@andrewrech you are a real user) I can't start this program so I wanted to find out if you can. A point to the Dockerfile to check the difference.

**Comment by AlexanderDilthey** [comment]
Hi @andrewrech 

Good idea, thank you for the suggestion! I'll implement it!

**Comment by AlexanderDilthey** [comment]
@andrewrech Would you mind sending a PR?

**Comment by andrewrech** [comment]
I can't get your software to build due to the hardlinked dependencies, sorry.

https://github.com/AlexanderDilthey/MHC-PRG/issues/28

**Comment by AlexanderDilthey** [comment]
@andrewrech I had missed MHC-PRG#28 - the issue you describe there is for HLA*PRG:LA, and not for HLA*PRG/MHC-PRG, right?

In any case, you're getting the error because you're trying to call the binary directly, and not via the Perl script that's used for inference. As soon as you use the Perl script (with a properly configured paths.ini, as described here on GitHub), these errors will disappear.

**Comment by andrewrech** [comment]
@AlexanderDilthey Yes, I'm sorry, just realized incorrect repo.

I will try this.

**Comment by andrewrech** [comment]
@AlexanderDilthey Thanks, I was able to get this working! In retrospect, I'm not sure how to structure the Makefile, it is perhaps best to explicitly tell the user to edit it, as you have done.

**Comment by 0xaf1f** [comment]
If you use `?=` to do the assignment, users will be able to override the value on the command line.

Like

```makefile
BOOST_INCLUDE ?= /hardcoded/path/to/boost/boost_1_64_0/install/include
BOOST_LIB ?= /hardcoded/path/to/boost/boost_1_64_0/install/lib
```
will allow for overriding those values when calling `make` by doing this:

```shell
make BOOST_INCLUDE=/my/boost/include BOOST_LIB=/my/boost/lib
```

**Comment by AlexanderDilthey** [comment]
@0xaf1f Great idea, I've changed the makefile accordingly.
