### ISSUE TITLE
how to support   DRB5  allele typing  result 

### ISSUE THREAD

**Issue by lidd77** [AlexanderDilthey/HLA-PRG-LA#118]
Dear professor
       
      I want to check  DRB5 allele typing from HLA-LA , but   unlucky,   I can not find that in this tool .
      so could you tell me how to support this  gene DRB5 allele typing ?

thank you !

**Comment by AlexanderDilthey** [comment]
Hi @lidd77, DRB5 is currently not supported and I have no specific plans for adding this gene. Sorry about that.
