### ISSUE TITLE
add additional reference for Ensembl human assembly 38

### ISSUE THREAD

**Issue by mforde84** [AlexanderDilthey/HLA-PRG-LA#13]
Hi, I would like to add this reference. idxstats shows the following:

1	248956422	5335060	0
10	133797422	2096960	0
11	135086622	3007088	0
12	133275309	2220636	0
13	114364328	1559146	0
14	107043718	3120738	0
15	101991189	1346306	0
16	90338345	1713268	0
17	83257441	2357610	0
18	80373285	618100	0
19	58617616	1441954	0
2	242193529	3693058	0
20	64444167	1508904	0
21	46709983	22438086	0
22	50818468	703842	0
3	198295559	3085302	0
4	190214555	1500350	0
5	181538259	2348104	0
6	170805979	3106762	0
7	159345973	2917186	0
8	145138636	2210556	0
9	138394717	2446060	0
MT	16569	147374	0
X	156040895	1218960	0
Y	57227415	37718	0
KI270728.1	1872759	1868	0
KI270727.1	448248	514	0
KI270442.1	392061	232	0
KI270729.1	280839	170	0
GL000225.1	211173	228	0
KI270743.1	210658	322	0
GL000008.2	209709	656	0
GL000009.2	201709	1044	0
KI270747.1	198735	254	0
KI270722.1	194050	82	0
GL000194.1	191469	1550	0
KI270742.1	186739	1588	0
GL000205.2	185591	2370	0
GL000195.1	182896	9600	0
KI270736.1	181920	44	0
KI270733.1	179772	9788058	0
GL000224.1	179693	1092	0
GL000219.1	179198	1092	0
KI270719.1	176845	2440	0
GL000216.2	176608	206	0
KI270712.1	176043	1692	0
KI270706.1	175055	1674	0
KI270725.1	172810	316	0
KI270744.1	168472	794	0
KI270734.1	165050	434	0
GL000213.1	164239	260	0
GL000220.1	161802	9727154	0
KI270715.1	161471	22	0
GL000218.1	161147	3756	0
KI270749.1	158759	206	0
KI270741.1	157432	48	0
GL000221.1	155397	1372	0
KI270716.1	153799	32	0
KI270731.1	150754	414	0
KI270751.1	150742	244	0
KI270750.1	148850	30	0
KI270519.1	138126	18	0
GL000214.1	137718	254	0
KI270708.1	127682	76	0
KI270730.1	112551	12	0
KI270438.1	112505	78	0
KI270737.1	103838	42	0
KI270721.1	100316	1604	0
KI270738.1	99375	70	0
KI270748.1	93321	624	0
KI270435.1	92983	34	0
GL000208.1	92689	30	0
KI270538.1	91309	4	0
KI270756.1	79590	6	0
KI270739.1	73985	4	0
KI270757.1	71251	0	0
KI270709.1	66860	34	0
KI270746.1	66486	154	0
KI270753.1	62944	22	0
KI270589.1	44474	2	0
KI270726.1	43739	24	0
KI270735.1	42811	32	0
KI270711.1	42210	5314	0
KI270745.1	41891	2244	0
KI270714.1	41717	516	0
KI270732.1	41543	20	0
KI270713.1	40745	185894	0
KI270754.1	40191	4	0
KI270710.1	40176	0	0
KI270717.1	40062	1294	0
KI270724.1	39555	6	0
KI270720.1	39050	116	0
KI270723.1	38115	14	0
KI270718.1	38054	966	0
KI270317.1	37690	0	0
KI270740.1	37240	0	0
KI270755.1	36723	54	0
KI270707.1	32032	104	0
KI270579.1	31033	0	0
KI270752.1	27745	2	0
KI270512.1	22689	0	0
KI270322.1	21476	0	0
GL000226.1	15008	0	0
KI270311.1	12399	0	0
KI270366.1	8320	0	0
KI270511.1	8127	0	0
KI270448.1	7992	0	0
KI270521.1	7642	0	0
KI270581.1	7046	0	0
KI270582.1	6504	4	0
KI270515.1	6361	0	0
KI270588.1	6158	0	0
KI270591.1	5796	0	0
KI270522.1	5674	0	0
KI270507.1	5353	0	0
KI270590.1	4685	0	0
KI270584.1	4513	0	0
KI270320.1	4416	0	0
KI270382.1	4215	2	0
KI270468.1	4055	0	0
KI270467.1	3920	16	0
KI270362.1	3530	0	0
KI270517.1	3253	0	0
KI270593.1	3041	0	0
KI270528.1	2983	0	0
KI270587.1	2969	0	0
KI270364.1	2855	0	0
KI270371.1	2805	0	0
KI270333.1	2699	0	0
KI270374.1	2656	0	0
KI270411.1	2646	0	0
KI270414.1	2489	0	0
KI270510.1	2415	0	0
KI270390.1	2387	0	0
KI270375.1	2378	0	0
KI270420.1	2321	0	0
KI270509.1	2318	0	0
KI270315.1	2276	0	0
KI270302.1	2274	4	0
KI270518.1	2186	0	0
KI270530.1	2168	0	0
KI270304.1	2165	0	0
KI270418.1	2145	0	0
KI270424.1	2140	0	0
KI270417.1	2043	0	0
KI270508.1	1951	0	0
KI270303.1	1942	0	0
KI270381.1	1930	0	0
KI270529.1	1899	0	0
KI270425.1	1884	0	0
KI270396.1	1880	0	0
KI270363.1	1803	6	0
KI270386.1	1788	0	0
KI270465.1	1774	0	0
KI270383.1	1750	0	0
KI270384.1	1658	0	0
KI270330.1	1652	20	0
KI270372.1	1650	0	0
KI270548.1	1599	0	0
KI270580.1	1553	6	0
KI270387.1	1537	0	0
KI270391.1	1484	0	0
KI270305.1	1472	0	0
KI270373.1	1451	0	0
KI270422.1	1445	0	0
KI270316.1	1444	0	0
KI270340.1	1428	0	0
KI270338.1	1428	0	0
KI270583.1	1400	0	0
KI270334.1	1368	0	0
KI270429.1	1361	0	0
KI270393.1	1308	0	0
KI270516.1	1300	0	0
KI270389.1	1298	0	0
KI270466.1	1233	12	0
KI270388.1	1216	0	0
KI270544.1	1202	0	0
KI270310.1	1201	0	0
KI270412.1	1179	0	0
KI270395.1	1143	0	0
KI270376.1	1136	0	0
KI270337.1	1121	0	0
KI270335.1	1048	0	0
KI270378.1	1048	0	0
KI270379.1	1045	2	0
KI270329.1	1040	0	0
KI270419.1	1029	0	0
KI270336.1	1026	0	0
KI270312.1	998	0	0
KI270539.1	993	4	0
KI270385.1	990	0	0
KI270423.1	981	0	0
KI270392.1	971	0	0
KI270394.1	970	0	0

however I'm not entirely sure how to format the knownReferences file.

Thanks for the help,
Martin

**Comment by AlexanderDilthey** [comment]
Hi Martin,

I've added a reference file. You can add it by doing a 'git pull' in your installation directory. Can you give it a try?

Just to confirm: I couldn't identify any alternative MHC or HLA contigs -- correct?

Cheers,

Alex
