### ISSUE TITLE
errors running test

### ISSUE THREAD

**Issue by xinyli** [AlexanderDilthey/HLA-PRG-LA#14]
Hi,

I am running the smaller test file provided with this command: ../src/HLA-PRG-LA.pl --BAM NA12878.mini.cram --graph ../graphs/PRG_MHC_GRCh38_withIMGT --sampleID NA12878 --maxThreads 7

It returns this error message: 
HLA-PRG-LA: mapper/bwa/BWAmapper.cpp:126: void mapper::bwa::BWAmapper::mapLong(std::string, std::string, std::string, bool, std::string): Assertion `(longMode == "pacbio") || (longMode == "ont2d")' failed.

I don't have any longMode input and it should not go to mapLong function. Is there any issues with my command or installation ? 

Thanks,
Sarah

**Comment by xinyli** [comment]
change the line 758 of HLA-PRG-LA.cpp should work : 
if(longReads.length() != 0) --> if(longReads != "0")

**Comment by xinyli** [comment]
Sorry, it seems that I still have some error message: 

Here is the output file:
 [ Wed Mar  7 12:35:57 2018 ] processBAM::processBAM(..): Start graph gap analysis.
 [ Wed Mar  7 12:36:01 2018 ] processBAM::processBAM(..) graph gap analysis: have 3494 graph gap stretches; criterion length >= 3
/apps/source/bwa/0.7.16a/bwa mem -t7 -M -a /data/srlab/xli/HLA-PRG-LA/src/../graphs/../graphs/PRG_MHC_GRCh38_withIMGT/mapping_PRGonly/referenceGenome.fa /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_1.fastq /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_2.fastq | /apps/lib-osver/samtools/1.4.1/bin/samtools view -Sb - > /data/srlab/xli/HLA-PRG-LA/working/NA12878/remapped_with_a.bam.unsorted
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 693070 sequences (70000070 bp)...
[M::process] read 693070 sequences (70000070 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (2, 4694, 0, 2)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (273, 318, 360)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (99, 534)
[M::mem_pestat] mean and std.dev: (315.84, 71.20)
[M::mem_pestat] low and high boundaries for proper pairs: (12, 621)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 97.021 CPU sec, 13.851 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 102, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (254, 307, 337)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (88, 503)
[M::mem_pestat] mean and std.dev: (294.76, 73.08)
[M::mem_pestat] low and high boundaries for proper pairs: (2, 587)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 89.072 CPU sec, 12.689 real sec
[M::process] read 693070 sequences (70000070 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 1, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 97.718 CPU sec, 13.939 real sec
[M::process] read 693070 sequences (70000070 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 32, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (284, 328, 385)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (82, 587)
[M::mem_pestat] mean and std.dev: (329.97, 87.15)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 688)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 94.063 CPU sec, 13.400 real sec
[M::process] read 693070 sequences (70000070 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 64.724 CPU sec, 9.194 real sec
[M::process] read 693070 sequences (70000070 bp)...
[M::process] read 302018 sequences (30503818 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 693070 reads in 67.702 CPU sec, 9.577 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 302018 reads in 27.585 CPU sec, 3.907 real sec
[main] Version: 0.7.16a-r1181
[main] CMD: /apps/source/bwa/0.7.16a/bwa mem -t7 -M -a /data/srlab/xli/HLA-PRG-LA/src/../graphs/../graphs/PRG_MHC_GRCh38_withIMGT/mapping_PRGonly/referenceGenome.fa /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_1.fastq /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_2.fastq
[main] Real time: 117.129 sec; CPU: 542.409 sec
/apps/lib-osver/samtools/1.4.1/bin/samtools sort /data/srlab/xli/HLA-PRG-LA/working/NA12878/remapped_with_a.bam.unsorted > /data/srlab/xli/HLA-PRG-LA/working/NA12878/remapped_with_a.bam
[bam_sort_core] merging from 3 files...
/apps/lib-osver/samtools/1.4.1/bin/samtools index /data/srlab/xli/HLA-PRG-LA/working/NA12878/remapped_with_a.bam
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
threads: 1
Done
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
HLA-PRG-LA execution not successful. Command was ../bin/HLA-PRG-LA --action HLA --maxThreads 7 --sampleID NA12878 --outputDirectory /data/srlab/xli/HLA-PRG-LA/working/NA12878 --PRG_graph_dir /data/srlab/xli/HLA-PRG-LA/src/../graphs/../graphs/PRG_MHC_GRCh38_withIMGT --FASTQ1 /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_1.fastq --FASTQ2 /data/srlab/xli/HLA-PRG-LA/working/NA12878/R_2.fastq --bwa_bin /apps/source/bwa/0.7.16a/bwa --samtools_bin /apps/lib-osver/samtools/1.4.1/bin/samtools --mapAgainstCompleteGenome 0 --longReads 0

Any idea how to fix this ?

**Comment by AlexanderDilthey** [comment]
This is a wrong code path. I'll get back to you later today or tomorrow.

**Comment by AlexanderDilthey** [comment]
Can you do a fresh pull, rebuild and retry? I think I've fixed it.

**Comment by xinyli** [comment]
Thanks. I will try and get back to you .
