### ISSUE TITLE
only for GRCh38?  not Hg19?

### ISSUE THREAD

**Issue by yaruchen** [AlexanderDilthey/HLA-PRG-LA#15]
I found the graph is named PRG_MHC_GRCh38_withIMGT ,  but my REF is hg19 ? can i use this soft to anlysis HLA ?

**Comment by AlexanderDilthey** [comment]
Yes. The program will automatically figure out what reference you use. Let me know if you run into any issues.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Theo612** [comment]
Hi @AlexanderDilthey, i have the same question for now. my ref is hg19, actually the program doing the same process like in 2018 ? Thank u
